[project]
name = "aga"
version = "0.1.0"
description = "Arian's Goofy Agents"
readme = "README.org"
requires-python = ">=3.13"
dependencies = [
  "beeai-framework[duckduckgo, wikipedia, mcp]"
]

[tool.pyright]
venvPath = "."
venv = ".venv"
